# Generated by Django 5.0.2 on 2024-02-12 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_liv', models.CharField(max_length=100, verbose_name='Employees_name')),
                ('Date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('ref_liv', models.CharField(default='', max_length=100, verbose_name='Employees_ref')),
                ('new_Reg', models.CharField(max_length=100, verbose_name='city')),
                ('Duration_TSP_minutes', models.IntegerField(default=0, verbose_name='Duration_TSP_minutes')),
                ('Route_Length', models.FloatField(default=0.0, verbose_name='Route_TSP_Length')),
                ('list_ref_clients', models.JSONField(default=list, verbose_name='list_ref_clients')),
                ('list_name_clients', models.JSONField(max_length=1000, verbose_name='list_name_clients')),
                ('URL_html', models.URLField(verbose_name='URL_html')),
            ],
        ),
    ]
